import { addArticle } from '../../utils/language';
import { getRandomEl } from '../../utils/math-functions';

const initialDescriptors = [
	'a lively and quirky',
	'a dynamic and offbeat',
	'a jubilant and spontaneous',
	'a radiant and imaginative',
	'a spirited and intrepid',
	'a fearless and creative',
	'a magnetic and unrestrained',
	'a vivacious and daring',
	'a dynamic and whimsical',
	'a relentless and vibrant',
	'a jubilant and bold',
	'a flamboyant and imaginative',
	'a daring and unbounded',
	'a vibrant and fearless',
	'a magnetic and spirited',
	'an energetic and unconventional',
	'an exuberant and unbridled',
	'an animated and spirited',
	'an unstoppable and free-spirited',
	'an animated and inventive',
	'an effervescent and inventive',
	'an audacious and carefree'
];
const individual = ['person', 'character', 'unique soul', 'soul'];
const strikingWords = [
	'remarkable',
	'impressive',
	'noteworthy',
	'extraordinary',
	'exceptional',
	'astonishing',
	'astounding',
	'stunning',
	'mind-blowing',
	'awe-inspiring',
	'breathtaking',
	'captivating',
	'phenomenal',
	'splendid',
	'majestic',
	'prodigious',
	'grandiose',
	'fantastic',
	'incredible',
	'outstanding',
	'superb',
	'marvelous',
	'striking',
	'unbelievable',
	'miraculous',
	'jaw-dropping',
	'dazzling',
	'eye-catching',
	'riveting',
	'masterful',
	'mesmerizing',
	'transcendent',
	'exquisite',
	'peerless',
	'unparalleled',
	'matchless',
	'unique',
	'incomparable',
	'singular',
	'inimitable',
	'unrivaled',
	'perfect',
	'consummate',
	'flawless',
	'sublime',
	'magnificent',
	'regal',
	'sumptuous',
	'opulent',
	'lavish',
	'splendiferous',
	'glorious',
	'wondrous',
	'captivating',
	'ravishing',
	'alluring',
	'enchanting',
	'bewitching',
	'charming',
	'delightful',
	'gorgeous',
	'splendorous',
	'dignified',
	'noble',
	'august',
	'imposing',
	'stately',
	'monumental',
	'commanding',
	'distinguished',
	'eminent',
	'renowned',
	'illustrious',
	'prestigious',
	'celebrated',
	'famous',
	'notable',
	'acclaimed',
	'laudable',
	'praised',
	'applauded',
	'commendable'
];
const hairColors = [
	'black',
	'brown',
	'blonde',
	'red',
	'auburn',
	'brunette',
	'white',
	'gray',
	'blue',
	'green',
	'purple',
	'pink',
	'silver',
	'dyed',
	'platinum',
	'caramel',
	'honey',
	'chestnut',
	'mahogany',
	'burgundy',
	'ash brown',
	'strawberry blonde',
	'golden blonde',
	'ash blonde',
	'dark red',
	'light brown',
	'sandy brown',
	'dirty blonde',
	'copper'
];
const hairTypes = [
	'short',
	'straight',
	'wavy',
	'curly',
	'coiled',
	'kinky',
	'spiral',
	'frizzy',
	'fine',
	'thick',
	'course',
	'smooth',
	'textured',
	'silky',
	'crinkled',
	'permed',
	'untamed',
	'frizz-free',
	'loose',
	'tight'
];
const eyeDescriptions = [
	'captivating',
	'hypnotic',
	'mesmerizing',
	'spellbinding',
	'radiant',
	'magnetic',
	'bewitching',
	'piercing',
	'sparkling',
	'glistening',
	'luminous',
	'soulful',
	'penetrating',
	'deep',
	'compelling',
	'spellbound',
	'charismatic',
	'riveting',
	'fascinating',
	'mysterious',
	'sensual',
	'dreamy',
	'hypnotizing',
	'radiant',
	'glimmering',
	'glinting',
	'twinkling',
	'shimmering',
	'gleaming',
	'flashy',
	'scintillating',
	'dazzling',
	'glowing',
	'lustrous',
	'beaming',
	'luminescent',
	'phosphorescent',
	'vibrant',
	'colorful',
	'fiery',
	'intoxicating',
	'enchanting',
	'lluring',
	'entrancing',
	'expressive',
	'intense',
	'ethereal',
	'enigmatic',
	'enrapturing',
	'enthralling',
	'invigorating',
	'engrossing',
	'bsorbing',
	'iridescent',
	'opalescent',
	'electric',
	'vivid',
	'piercing',
	'perceptive',
	'observant',
	'discerning',
	'sharp',
	'wise',
	'judicious',
	'insightful',
	'stute',
	'intelligent',
	'knowing',
	'knowledgeable',
	'sagacious',
	'thoughtful',
	'reflective',
	'contemplative',
	'profound',
	'wise',
	'deep',
	'insightful',
	'philosophical',
	'pensive',
	'musing',
	'meditative',
	'cogitative',
	'ruminative',
	'brooding',
	'deliberate',
	'calculating',
	'meticulous',
	'precise',
	'methodical',
	'organized',
	'systematic',
	'orderly',
	'structured',
	'logical',
	'rational',
	'reasoned',
	'coherent',
	'integrated',
	'consistent',
	'thorough',
	'comprehensive',
	'exhaustive',
	'detailed',
	'analytical',
	'scrutinizing',
	'examining',
	'investigative',
	'inquisitive',
	'curious',
	'piercing',
	'searching',
	'inspective',
	'insightful',
	'judicious',
	'thoughtful',
	'reflective',
	'contemplative',
	'profound',
	'inspired',
	'original',
	'unique'
];
const eyeColors = [
	'brown',
	'amber',
	'hazel',
	'green',
	'blue',
	'gray',
	'violet',
	'black',
	'silver',
	'teal',
	'indigo',
	'olive',
	'copper',
	'steel',
	'pink',
	'lavender',
	'charcoal',
	'chestnut',
	'mahogany',
	'plum',
	'almond',
	'taupe',
	'forest green',
	'sky blue',
	'ocean blue',
	'chocolate',
	'coal',
	'rose gold'
];

const buildDescriptions = [
	'look lithe and lean, exuding an agile and graceful presence',
	'have a robust physique, radiating strength and vitality',
	'have an athletic build, embodying a dynamic and energetic lifestyle',
	'maintain a sculpted form, suggesting a dedication to fitness',
	'possess a sinewy frame, hinting at flexibility and resilience',
	'sport a muscular silhouette, projecting power and endurance',
	'display a toned body, reflecting a commitment to a healthy lifestyle',
	'appear gracefully muscular, combining strength with elegance',
	'show off an athletic and chiseled physique, showcasing a disciplined fitness routine',
	'maintain a well-defined physique, indicative of dedication to wellness',
	'possess a compact and powerful build, embodying strength in a smaller frame',
	'appear nimble and sculpted, with an emphasis on precision and control',
	'display a ripped and resilient physique, demonstrating both strength and durability',
	'show a shapely and strong form, balancing form and function seamlessly',
	'exhibit a dynamic build, suggesting versatility and adaptability',
	'radiate a buoyant physique, projecting a lively and vibrant energy',
	'display a toned and trim physique, embodying a sleek and streamlined appearance',
	'present a muscle-bound build, showcasing a powerful and imposing figure',
	'maintain a lean and mean appearance, portraying a focused and disciplined demeanor',
	'appear graceful and muscular, marrying strength with finesse',
	'display a compact and athletic physique, indicating prowess in agility and speed',
	'exhibit a solid and sculpted build, exhibiting a well-crafted physique',
	'show a sinewy and strong frame, with an emphasis on endurance and stamina',
	'display a toned and tough physique, projecting a resilient and tenacious character',
	'appear lithe and powerful, combining grace with underlying strength',
	'maintain a well-toned and resilient physique, suggesting both elegance and toughness',
	'display a dynamic and defined build, capturing a balance of power and precision',
	'show a muscle-carved physique, hinting at a commitment to sculpting',
	'radiate a buoyant and brawny physique, embodying both vitality and strength',
	'display a sculpted and spirited build, showcasing a lively and dynamic presence',
	'show a toned and tenacious appearance, projecting a determined and resilient spirit',
	'have an athletic and assertive build, reflecting a bold and active personality',
	'appear flexible and formidable, combining adaptability with strength',
	'maintain a well-sculpted and spirited physique, radiating an energetic and lively aura',
	'look lackluster, suggesting a sedentary lifestyle',
	'have a flabby frame, indicative of a lack of physical activity',
	'have an untoned body, implying a disregard for fitness',
	'have a frail silhouette, hinting at a lack of strength and endurance',
	'have an overweight form, projecting a sedentary and unhealthy appearance',
	'have a shapeless physique, lacking definition and muscle tone',
	'have a slovenly build, reflecting a neglect of physical well-being',
	'have a feeble frame, suggesting a lack of vitality and energy',
	'have an unfit silhouette, showcasing a general lack of physical conditioning',
	'have a soft and pudgy appearance, indicating a lack of commitment to fitness',
	'look awkward and ungainly, lacking grace and physical coordination',
	'have a fragile physique, embodying a vulnerability to physical challenges',
	'have an unathletic build, indicating a disinterest in sports and exercise',
	'have an out-of-shape silhouette, reflecting a sedentary and unhealthy lifestyle',
	'have a doughy and weak appearance, projecting a lack of strength and resilience',
	'have a sluggish physique, suggesting a lack of energy and dynamism',
	'have a shapeless and out-of-condition form, displaying a disregard for physical health',
	'have an unsculpted form, lacking the definition and contours of a fit body',
	'have an unimpressive build, failing to convey a sense of strength or fitness',
	'have a soft and flimsy physique, lacking the firmness and solidity of a well-conditioned body',
	'look awkward and uncoordinated, demonstrating a lack of physical prowess',
	'have an unhealthy silhouette, indicating a poor state of physical well-being',
	'have an unfit and sluggish appearance, projecting a lack of endurance and stamina',
	'appear awkward and ponderous, lacking the agility and nimbleness of a fit physique',
	'have an untoned and lethargic look, suggesting a lack of motivation for physical activity',
	'have a shapeless and feeble physique, conveying a sense of physical weakness',
	'have an unimposing build, failing to command attention or convey physical presence',
	'have an unathletic and feeble appearance, lacking the vitality and vigor associated with fitness',
	'appear unfit and listless, indicating a lack of energy and enthusiasm for physical activity',
	'have an unremarkable physique, lacking distinctive features or attributes',
	'have an unsculpted and uninspiring form, failing to evoke admiration or interest',
	'have an untoned and uninspiring appearance, suggesting a lack of commitment to personal fitness',
	'have a shapeless and uninspiring physique, lacking the qualities that define a fit and healthy body',
	'have an unimpressive and unremarkable look, failing to leave a lasting or positive impression'
];

const strikingPhysicalFeatures = [
	'have one eye that is blind',
	'wear a tattoo of an ancient symbol on their forearm',
	'bear an intricate scar across their cheek, a testament to past battles',
	'have a distinctive limp from an old injury, yet move with grace',
	'might wear a mask to conceal their true identity',
	'have a voice that carries an enchanting or haunting melody',
	'possess an unusual birthmark that seems to shimmer faintly',
	'always have a peculiar scent, reminiscent of a rare and exotic flower',
	'sport a set of ornate and mysterious tattoos across their body',
	'have an unnatural calmness in their eyes, revealing deep wisdom',
	'have a constellation of freckles that forms an intricate pattern on their cheeks and nose',
	'have a small, mysterious birthmark shaped like a crescent moon above their lip',
	'have piercing eyes with heterochromia, each eye a different mesmerizing color',
	'have a delicate beauty mark just below the corner of one eye, enhancing their allure',
	'have a scar in the shape of a lightning bolt, giving them a striking and bold appearance',
	'have a perfectly symmetrical set of dimples that appear when they smile, adding charm',
	'have a silver or gold lip ring that glints in the light, giving them a hint of rebellion',
	'have a single, ethereal tear-shaped crystal embedded in the corner of one eye',
	'have a series of tiny, luminescent dots that trace an elegant pattern on their temples',
	'have a meticulously groomed and colorful facial hair that captures your attention'
];

export function generateNpcDescriptions(worldObj) {
	worldObj.npcs.forEach((npc) => {
		npc.description = `${getRandomEl(initialDescriptors)} ${getRandomEl(
			individual
		)} with ${addArticle(getRandomEl(strikingWords))} ${getRandomEl(hairColors)}, ${getRandomEl(
			hairTypes
		)} hair. Their eyes are ${addArticle(getRandomEl(eyeDescriptions))} shade of ${getRandomEl(
			eyeColors
		)}, and they ${getRandomEl(buildDescriptions)}. They ${getRandomEl(strikingPhysicalFeatures)}.`;
	});
}
